---
# This playbook reverts a snapshot for a VM managed by a vcenter server
- name: Revert VMware Snapshot
  hosts: all
  vars:
    vcenter_server: thatserver.parmstrong.ca
    snap_name: SomeSnap
  
  tasks:  
  - name: Revert to a snapshot
    vmware_guest_snapshot:
      hostname: {{ vcenter_server }}
      name: {{ ansible_hostname }}
      state: revert
      snapshot_name: {{ snap_name }}
