---
# This playbook reverts a snapshot for a VM managed by a vcenter server
- name: Revert VMware Snapshot
  hosts: localhost
  vars:
    vcenter_server: vsphere.parmstrong.ca
    datacenter_name: parmstrong.ca
    vm_hostname: webserverdemo.parmstrong.ca
    snap_name: BeforeDemo
  
  tasks:  
  - name: Revert to a snapshot
    vmware_guest_snapshot:
      state: revert
      datacenter: '{{ datacenter_name }}'
      hostname: '{{ vcenter_server }}'
      name: '{{ vm_hostname }}'
      snapshot_name: '{{ snap_name }}'
